### ISSUE TITLE
Another problem with the meteor_autoupdate_clientVersions collection

### ISSUE THREAD

**Issue by jamesgibson14** [cult-of-coders/redis-oplog#108]
Exception from sub meteor_autoupdate_clientVersions id G22dEfbMWhmP9pLqe TypeError: Cannot read
property 'selector' of undefined
at Object.Future.wait (/home/james/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x
86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
 at [object Object]._.extend.runTask (packages/meteor.js:741:9)
  at Subscription.<anonymous> (packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:37:34
)

**Comment by jamesgibson14** [comment]
I have `overridePublishFunction: true` which is why this collection keep coming up.

**Comment by theodorDiaconu** [comment]
@jamesgibson14 ok got it!
