### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by maxnowack** [cult-of-coders/redis-oplog#125]
I've seen an exception in my server logs. I'm not sure where it's coming from.

````
Exception in queued task: TypeError: Cannot read property 'length' of undefined
    at packages/cultofcoders:redis-oplog/lib/cache/lib/filterFieldsForFetching.js:9:29
    at Array.forEach (native)
    at filterAllowedFields (packages/cultofcoders:redis-oplog/lib/cache/lib/filterFieldsForFetching.js:8:20)
    at ObservableCollection._changeNormal (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:231:26)
    at ObservableCollection.change (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:175:40)
    at handleUpdate (packages/cultofcoders:redis-oplog/lib/processors/default.js:43:34)
    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/default.js:15:13)
    at Object.task (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:53:13)
    at [object Object]._.extend._run (packages/meteor.js:807:18)
    at packages/meteor.js:785:14
````

**Comment by theodorDiaconu** [comment]
Most likely a malformed options.fields. Made it throw an exception if could not properly extract fields.
