### ISSUE TITLE
MeteorToys + Redis-oplog throw this error

### ISSUE THREAD

**Issue by Fen747** [cult-of-coders/redis-oplog#130]
Using redis-oplog in the same project than meteor toys Pro, after I did a `meteor update` from 1.4.2.3 to 1.4.2.7 (and almost all the packages in my app), I now get this when I start my app :

```
Exception while invoking method 'MeteorToys_impersonate_account' { stack: 'TypeError: Cannot read property \'find\' of undefined\n    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/actions/requery.js:14:22)\n    at handleRemove (packages/cultofcoders:redis-oplog/lib/processors/limit-sort.js:72:9)\n    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/limit-sort.js:20:13)\n    at RedisSubscriber.processSync (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:65:9)\n    at packages/cultofcoders:redis-oplog/lib/mongo/lib/compensateForLatency.js:19:28\n    at Array.forEach (native)\n    at packages/cultofcoders:redis-oplog/lib/mongo/lib/compensateForLatency.js:18:25\n    at Array.forEach (native)\n    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/mongo/lib/compensateForLatency.js:13:14)\n    at packages/cultofcoders:redis-oplog/lib/mongo/lib/dispatchers.js:36:9',
I20170216-13:00:38.373(1)?   source: 'method' }
```

`versions` file before the update (1.4.2.3) : http://pastebin.com/CR9MxWhC
`versions` file after the update (1.4.2.7) : http://pastebin.com/8vuKXyHM

**Comment by theodorDiaconu** [comment]
@Fen747 just add redis-oplog before MeteorToys because it needs to load a package that is aware of all collections.

**Comment by theodorDiaconu** [comment]
dburles:mongo-collection-instances@0.3.5
this package :)
