### ISSUE TITLE
[Meteor 1.5] TypeError: callback is not a function

### ISSUE THREAD

**Issue by dnish** [cult-of-coders/redis-oplog#157]
Hey,
when executing this on the server side:

```
Messages.remove({createdAt: {$lt: messageDate}}, {pushToRedis: false});
```

I get the following exception:
```
I20170609-12:03:05.139(2)? Exception in callback of async function: TypeError: callback is not a function
I20170609-12:03:05.142(2)?     at packages/mongo/collection.js:650:5
I20170609-12:03:05.144(2)?     at runWithEnvironment (packages/meteor.js:1176:24)
I20170609-12:03:05.169(2)?     at packages/meteor.js:1189:14
I20170609-12:03:05.184(2)?     at packages/mongo/mongo_driver.js:320:7
I20170609-12:03:05.185(2)?     at runWithEnvironment (packages/meteor.js:1176:24)
```

**Comment by dnish** [comment]
Okay, I see that this happens when Redis-Oplog isn't initialized (like on our dev machine). It works after initialization.
