### ISSUE TITLE
Getting an error with optimistic UI

### ISSUE THREAD

**Issue by MaxShv** [cult-of-coders/redis-oplog#162]
Any idea on how to resolve it?

 TypeError: Cannot read property 'id' of null
     at PublicationEntry.send (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:103:31)
    at ObservableCollection.send (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:138:9)
     at ObservableCollection.change (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:205:14)
     at handleUpdate (packages/cultofcoders:redis-oplog/lib/processors/default.js:43:34)
     at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/default.js:15:13)
     at RedisSubscriber.processSync (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:65:9)
     at packages/cultofcoders:redis-oplog/lib/mongo/lib/compensateForLatency.js:19:28
     at Array.forEach (native)
     at packages/cultofcoders:redis-oplog/lib/mongo/lib/compensateForLatency.js:18:25
     at Array.forEach (native)
  => awaited here:
     at Promise.await (/Users/max/.meteor/packages/promise/.0.8.8.se4chr++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:39:12)

    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1624:22)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1593:17)
    at Object.Meteor.users.find.observe.added (imports/startup/server/batch-jobs.js:301:6)
    at Object.added (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:54:26)
    at packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:145:28
    at Function._.each._.forEach (packages/underscore.js:147:22)
    at PublicationEntry._performInitialAddForObserver (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:140:11)
    at PublicationEntry.addObserver (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:58:18)
    at PublicationFactory.create (packages/cultofcoders:redis-oplog/lib/cache/PublicationFactory.js:34:26)

**Comment by theodorDiaconu** [comment]
@MaxShv can you help me reproduce this ? in a repo ?
