### ISSUE TITLE
Error with meteor-collection-helpers

### ISSUE THREAD

**Issue by elledienne** [cult-of-coders/redis-oplog#167]
Seems like this package doesn't really work well with `meteor-collection-helpers`. When I run my app I get this error

```
Exception from sub <sub-name> id jh5rrABxbg6yYZKwr TypeError: <document>.<helper-function-name> is not a function
    at transformer (webpack:///server/publications/deals.js:60:1)
    at Object.added (webpack:///server/publications/deals.js:78:1)
    at Object.added (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:54:26)
    at packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:145:28
    at Function._.each._.forEach (packages/underscore.js:147:22)
    at PublicationEntry._performInitialAddForObserver (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:140:11)
    at PublicationEntry.addObserver (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:58:18)
    at PublicationFactory.create (packages/cultofcoders:redis-oplog/lib/cache/PublicationFactory.js:34:26)
    at create (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:18:37)
    at [object Object].cursor.observe (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:40:16)
```

The problem here is that the document doesn't get extended with the `meteor-collection-helpers` helpers. Do you have any idea why that doesn't happen?

**Comment by theodorDiaconu** [comment]
@elledienne it seems that cloneDeep function does not copy the extended functions as well. very interesting. ok, got it, thanks for bug report.

**Comment by theodorDiaconu** [comment]
@elledienne can you explain this:  at transformer (webpack:///server/publications/deals.js:60:1) ?
