### ISSUE TITLE
Error: [When you subscribe directly, you can not have other specified fields rather than $in]

### ISSUE THREAD

**Issue by ixdi** [cult-of-coders/redis-oplog#170]
Does anyone know why this error is happening?

We use publish composite. We have only noticed the error in production log, so for now we can not know which fields were used in the subscription. It only happens very occasionally.

Thank you

```js
Exception in callback of async function: Error: [When you subscribe directly, you can not have other specified fields rather than $in]
2017-08-07 17:31:23+02:00 at packages/cultofcoders:redis-oplog/lib/utils/extractIdsFromSelector.js:9:19
2017-08-07 17:31:23+02:00 at RedisSubscriber.getChannels (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:40:29)
2017-08-07 17:31:23+02:00 at new RedisSubscriber (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:21:30)
2017-08-07 17:31:23+02:00 at PublicationEntry.init (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:42:32)
2017-08-07 17:31:23+02:00 at new PublicationEntry (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:22:14)
2017-08-07 17:31:23+02:00 at PublicationFactory.create (packages/cultofcoders:redis-oplog/lib/cache/PublicationFactory.js:28:32)
2017-08-07 17:31:23+02:00 at create (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:18:37)
2017-08-07 17:31:23+02:00 at [object Object].cursor.observe (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:40:16)
2017-08-07 17:31:23+02:00 at Publication.publish (packages/reywood:publish-composite/lib/publication.js:34:42)
2017-08-07 17:31:23+02:00 at Publication.createChildPublication (packages/reywood:publish-composite/lib/publication.js:99:17)
2017-08-07 17:31:23+02:00 at Array.forEach (native)
2017-08-07 17:31:23+02:00 at Function._.each._.forEach (packages/underscore.js:139:11)
2017-08-07 17:31:23+02:00 at Publication._publishChildrenOf (packages/reywood:publish-composite/lib/publication.js:96:11)
2017-08-07 17:31:23+02:00 at packages/reywood:publish-composite/lib/publication.js:46:26
2017-08-07 17:31:23+02:00 at runWithEnvironment (packages/meteor.js:1180:24)
2017-08-07 17:31:23+02:00 at Object.added (packages/meteor.js:1193:14)
```

**Comment by theodorDiaconu** [comment]
@ixdi do you know what publication it is ? If yes paste it.

The reason is this:
We subscribe intelligently when you have a selector like `{ _id: {$in: [1,2,3]} }` 
However you may have something like { _id: {$nin: [1,2,3]} }, that may trigger an exception. Which is not good!

Pls show us the publication if you know it, or if you have something similar to what I said above.

**Comment by ixdi** [comment]
@theodorDiaconu 
We have selectors like { owner: {$in: [1,2,3]} } combined with { date: { $gte: start, $lte: end }} in the same selector.

```js
CollectionName.find({
    teamId,
    owner: { $in: groups },
    date: {
      $gte: start,
      $lte: end,
    },
  }, {
    fields: {
      date: 1,
      duration: 1,
      name: 1,
      teamId: 1,
      owner: 1,
    },
    sort: {
      createdAt: 1,
    },
  });
```
We still have not detected the publication that causes the problem, so this is only an example of our  type of publications. Our other publications only use $in.

**Comment by theodorDiaconu** [comment]
@ixdi this is closely related with _id, other fields should not affect that.

**Comment by theodorDiaconu** [comment]
@ixdi what is the status of this ?

**Comment by ixdi** [comment]
Hi,
By now, we have not had any issue with Meteor 1.6 (beta and rc).
I do not understand why but it seems correct now.
Thanks

**Comment by tscizzle** [comment]
I'm running into this as well, and it appears to be because we have a subscription filter like
```
{ _id: { _str: 'f4h85ogiuf30f8u9ij3' } }
```
which is an object, so redis-oplog wants it to have `$in`, but it's only an object because the `_id` is an `ObjectId`.

Filtering on an individual `ObjectId` should be ok, right?

So I'd classify that as a bug I guess, and think the check for `_.isObject(filter)` in `extractIdsFromSelector.js` should somehow account for objects that could be the value of an `_id`.

(Not sure what that check actually is. Maybe just check for `_str` since ObjectId would be the most common object that is still ok without an `$in`?)

**Comment by theodorDiaconu** [comment]
I think you're right, we should do the check for _str. File a new bug since I believe this is a different issue. Thanks
