### ISSUE TITLE
Problem with service-configuration package with redis-oplog 1.2.6

### ISSUE THREAD

**Issue by aboire** [cult-of-coders/redis-oplog#242]
I updated meteor to version 1.6.1, redis-oplog was upgraded to version 1.2.6, redis-oplog is loaded at the top of packages and my configuration comes from settings, and when I start the application, I have this error back : 
Error: [We could not properly identify the collection by its name: meteor_accounts_loginServiceConfiguration. Make sure you added redis-oplog package before any package that instantiates a collection.

**Comment by theodorDiaconu** [comment]
@aboire this is very strange.. quick repo pls ?

**Comment by theodorDiaconu** [comment]
@aboire do you still have this issue ?

**Comment by aboire** [comment]
yes I still have this problem

**Comment by theodorDiaconu** [comment]
@aboire can you do a quick repo, can't reproduce.

**Comment by hayk94** [comment]
I am having this issue as well.

This is the redis oplog version
`cultofcoders:redis-oplog@1.2.6_2`

And here is my packages file

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

cultofcoders:redis-oplog
disable-oplog
meteor-base@1.3.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.4.2                   # The database Meteor supports right now
blaze-html-templates@1.0.4 # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.4.0   # CSS minifier run for production mode
es5-shim@4.7.0                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.10.0              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.1            # Server-side component of the `meteor shell` command


react-meteor-data
accounts-password@1.5.0
accounts-google@1.3.1
accounts-base@1.4.2
practicalmeteor:mocha
xolvio:cleaner
service-configuration@1.0.11
email@1.2.3
froatsnook:shopify
fortawesome:fontawesome
yasaricli:search
google-config-ui@1.0.0
splendido:accounts-meld
dynamic-import@0.3.0
mrt:external-file-loader
babrahams:undo-redo
tmeasday:publish-counts
abernix:standard-minifier-js
meteorhacks:aggregate
momentjs:moment
simple:rest
simple:json-routes
msavin:sjobs

```

**Comment by theodorDiaconu** [comment]
@hayk94 can you do a quick repo for me please ?

**Comment by hayk94** [comment]
@theodorDiaconu yup I'll add the link soon.

**Comment by hayk94** [comment]
@theodorDiaconu here is the repo
https://github.com/hayk94/redisOplogIssue

**Comment by hayk94** [comment]
@theodorDiaconu any news?

**Comment by evolross** [comment]
I just started getting this issue upon adding `cultofcoders:redis-oplog@1.2.6_2` to my project. I'm on Meteor 1.5.1. Happens on startup of my app.

Is anyone seeing a negative consequence to this?

Stack trace:
```
I20180319-15:55:40.769(-7)? Exception from task: Error: [We could not properly identify the collection by its name: meteor_accounts_loginServiceConfiguration. Make sure you added redis-oplog package before any package that instantiates a collection.]
I20180319-15:55:40.770(-7)?     at new ObservableCollection (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:68:19)
I20180319-15:55:40.772(-7)?     at new PublicationEntry (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:19:37)
I20180319-15:55:40.773(-7)?     at PublicationFactory.create (packages/cultofcoders:redis-oplog/lib/cache/PublicationFactory.js:40:32)
I20180319-15:55:40.774(-7)?     at packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:52:44
I20180319-15:55:40.775(-7)?     at Array.forEach (native)
I20180319-15:55:40.775(-7)?     at packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:50:33
I20180319-15:55:40.776(-7)?     at runWithEnvironment (packages/meteor.js:1180:24)
I20180319-15:55:40.777(-7)?     at Object.task (packages/meteor.js:1193:14)
I20180319-15:55:40.777(-7)?     at [object Object]._.extend._run (packages/meteor.js:811:18)
I20180319-15:55:40.779(-7)?     at packages/meteor.js:789:14
```

**Comment by hayk94** [comment]
@evolross yup!
You cannot login with any service. Only email and password.

**Comment by theodorDiaconu** [comment]
On it!

**Comment by hayk94** [comment]
@theodorDiaconu great! do you have any idea when to expect the new release?

**Comment by theodorDiaconu** [comment]
@hayk94 today or latest monday :) cheers. Lots of other work done in background.
