### ISSUE TITLE
Not compatible with https://atmospherejs.com/slava/redis-livedata

### ISSUE THREAD

**Issue by AesSedai** [cult-of-coders/redis-oplog#247]
Following error when trying to use Meteor.RedisCollection

```
Exception from task: Error: [We could not properly identify the collection by its name: redis. Make sure you added redis-oplog package before any package that instantiates a collection.]
    at new ObservableCollection (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:55:19)
    at new PublicationEntry (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:19:37)
    at PublicationFactory.create (packages/cultofcoders:redis-oplog/lib/cache/PublicationFactory.js:40:32)
    at packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:50:40
    at Array.forEach (native)
    at packages/cultofcoders:redis-oplog/lib/publishWithRedis.js:48:29
    at runWithEnvironment (packages/meteor.js:1189:24)
    at Object.task (packages/meteor.js:1202:14)
    at [object Object].SQp._run (packages/meteor.js:820:16)
    at packages/meteor.js:797:12
```

packages:

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

cultofcoders:redis-oplog
disable-oplog

meteor-base@1.1.0             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.19                   # The database Meteor supports right now
reactive-var@1.0.11            # Reactive variable for tracker
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.3                 # Meteor's client-side reactive programming library

es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.8.1              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.4            # Server-side component of the `meteor shell` command

blaze-html-templates@1.0.4
kadira:blaze-layout

accounts-password@1.4.0
useraccounts:core
useraccounts:bootstrap
useraccounts:iron-routing

seba:minifiers-autoprefixer
fourseven:scss
aldeed:simple-schema
aldeed:collection2
simple:reactive-method
meteorhacks:subs-manager
session@1.1.7
raix:handlebar-helpers
percolate:synced-cron
chrismbeckett:toastr
oaf:moment-duration-format
lbee:moment-helpers
meteorhacks:kadira
mizzao:timesync
cesarve:simple-chat
ddp-rate-limiter@1.0.7
aldeed:template-extension
sha@1.0.9
slava:redis-livedata
check@1.2.5
meteorhacks:cluster
standard-minifier-js@2.1.1
mrt:fancybox
dynamic-import
react-template-helper
http
```

instantiator:

```
const redis = new Meteor.RedisCollection('redis');
```

then the redis collection was used the same way a normal collection is used.

**Comment by ramezrafla** [comment]
Did you follow the instructions in the readme and docs? This library is not meant to be compatible with Slava’s (and likely will never be).

**Comment by AesSedai** [comment]
I read through it, but I didn't see any mention of Slava's package so I thought I'd go ahead and try adding redis-oplog to my project to see if it would work. There wasn't an open issue about this, thought I'd bring it up. If it's not intended to be compatible then that's good to know, maybe I'll be able to refactor to not use Slava's.
