### ISSUE TITLE
Conflict with accounts-meld?

### ISSUE THREAD

**Issue by hayk94** [cult-of-coders/redis-oplog#248]
So I just added redis-oplog to my project

```
meteor add cultofcoders:redis-oplog
meteor add disable-oplog
```

With its default settings

And I get this error

```
W20180226-10:52:11.373(4)? (STDERR) Error: use "new" to construct a Mongo.Collection
W20180226-10:52:11.374(4)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:30:11)
W20180226-10:52:11.374(4)? (STDERR)     at packages/splendido_accounts-meld.js:116:15
W20180226-10:52:11.374(4)? (STDERR)     at packages/splendido_accounts-meld.js:702:4
W20180226-10:52:11.374(4)? (STDERR)     at packages/splendido_accounts-meld.js:751:4
W20180226-10:52:11.374(4)? (STDERR)     at packages/splendido_accounts-meld.js:764:3
W20180226-10:52:11.374(4)? (STDERR)     at infos.forEach.info (/Users/hayksafaryan/projects/b2c/.meteor/local/build/programs/server/boot.js:414:13)
W20180226-10:52:11.374(4)? (STDERR)     at Array.forEach (<anonymous>)
W20180226-10:52:11.375(4)? (STDERR)     at /Users/hayksafaryan/projects/b2c/.meteor/local/build/programs/server/boot.js:413:9
W20180226-10:52:11.375(4)? (STDERR)     at /Users/hayksafaryan/projects/b2c/.meteor/local/build/programs/server/boot.js:463:5
W20180226-10:52:11.375(4)? (STDERR)     at Function.run (/Users/hayksafaryan/projects/b2c/.meteor/local/build/programs/server/profile.js:510:12)
=> Exited with code: 1
```
It seems there is a conflict with this package
https://github.com/splendido/meteor-accounts-meld

**Comment by theodorDiaconu** [comment]
@hayk94 the error is triggered here: ```at new Mongo.Collection (packages/mongo/collection.js:30:11)```

Are you sure this is a redis-oplog issue ? :) They changed this in Meteor 1.6.1

**Comment by hayk94** [comment]
@theodorDiaconu I am not sure but this error happens only when I add redis-oplog to my packages so thought to let you know just in case.
I'll update to 1.6.1 and see what will happen.

**Comment by hayk94** [comment]
Updating to 1.6.1 solved the issue.
