### ISSUE TITLE
server rendering problem (meteor 1.6.1)

### ISSUE THREAD

**Issue by minhna** [cult-of-coders/redis-oplog#249]
I recently tested redis oplog with a sharded mongodb and it works beautifully.
But when I tried it with server render feature, it doesn't work.
Here are some server errors:
```
Mar 07 10:16:35 code-1 demo[2523]: events.js:183
Mar 07 10:16:35 code-1 demo[2523]:       throw er; // Unhandled 'error' event
Mar 07 10:16:35 code-1 demo[2523]:       ^
Mar 07 10:16:35 code-1 demo[2523]: Error: Can't wait without a fiber
Mar 07 10:16:35 code-1 demo[2523]:     at Function.wait (/home/demo/meteor-ssr-redis/bundle/programs/server/node_modules/fibers/future.js:159:9)
Mar 07 10:16:35 code-1 demo[2523]:     at Future.wait (/home/demo/meteor-ssr-redis/bundle/programs/server/node_modules/fibers/future.js:448:10)
Mar 07 10:16:35 code-1 demo[2523]:     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1018:47)
Mar 07 10:16:35 code-1 demo[2523]:     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1052:22)
Mar 07 10:16:35 code-1 demo[2523]:     at SynchronousCursor.map (packages/mongo/mongo_driver.js:1062:10)
Mar 07 10:16:35 code-1 demo[2523]:     at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1086:17)
Mar 07 10:16:35 code-1 demo[2523]:     at Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:876:44)
Mar 07 10:16:35 code-1 demo[2523]:     at module.exportDefault.withTracker (imports/ui/components/test/simpleSchema.js:98:37)
Mar 07 10:16:35 code-1 demo[2523]:     at ReactMeteorDataComponent.getMeteorData (packages/react-meteor-data/ReactMeteorData.jsx:181:16)
Mar 07 10:16:35 code-1 demo[2523]:     at MeteorDataManager.calculateData (packages/react-meteor-data/ReactMeteorData.jsx:34:24)
Mar 07 10:16:35 code-1 demo[2523]:     at ReactMeteorDataComponent.componentWillMount (packages/react-meteor-data/ReactMeteorData.jsx:130:45)
Mar 07 10:16:35 code-1 demo[2523]:     at za (/home/demo/meteor-ssr-redis/bundle/programs/server/npm/node_modules/react-dom/cjs/react-dom-server.
Mar 07 10:16:35 code-1 demo[2523]:     at a.render (/home/demo/meteor-ssr-redis/bundle/programs/server/npm/node_modules/react-dom/cjs/react-dom-s
Mar 07 10:16:35 code-1 demo[2523]:     at a.read (/home/demo/meteor-ssr-redis/bundle/programs/server/npm/node_modules/react-dom/cjs/react-dom-ser
Mar 07 10:16:35 code-1 demo[2523]:     at b._read (/home/demo/meteor-ssr-redis/bundle/programs/server/npm/node_modules/react-dom/cjs/react-dom-se
Mar 07 10:16:35 code-1 demo[2523]:     at b.Readable.read (_stream_readable.js:442:10)
Mar 07 10:16:35 code-1 demo[2523]:     at nReadingNextTick (_stream_readable.js:797:8)
Mar 07 10:16:35 code-1 demo[2523]:     at _combinedTickCallback (internal/process/next_tick.js:135:11)
Mar 07 10:16:35 code-1 demo[2523]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Mar 07 10:16:36 code-1 systemd[1]: demo.meteor.ssr.redis.service: Main process exited, code=exited, status=1/FAILURE
Mar 07 10:16:36 code-1 systemd[1]: demo.meteor.ssr.redis.service: Unit entered failed state.
Mar 07 10:16:36 code-1 systemd[1]: demo.meteor.ssr.redis.service: Failed with result 'exit-code'.
Mar 07 10:16:36 code-1 systemd[1]: demo.meteor.ssr.redis.service: Service hold-off time over, scheduling restart.
Mar 07 10:16:36 code-1 systemd[1]: Stopped demo.meteor.ssr.redis.service.
Mar 07 10:16:36 code-1 systemd[1]: Started demo.meteor.ssr.redis.service.
```
The demo app repository here: https://github.com/minhna/meteor-ssr-redis-oplog.git
The problem on the `/test` page.

**Comment by ramezrafla** [comment]
Maybe you need to be running your code in Meteor.bindEnvironment?

**Comment by minhna** [comment]
I don't have any problems with the default meteor pub/sub. Where can I add `Meteor.bindEnvironment` to?

**Comment by minhna** [comment]
Update: it doesn't work with `renderToNodeStream` and server side rendering. I moved to `renderToString` and it works now.
