### ISSUE TITLE
v2.0.0 users

### ISSUE THREAD

**Issue by flean** [cult-of-coders/redis-oplog#317]
I just upgraded to 2.0.0 and had this issue, I didn't have this before any help would be great. Thanks

```
2019-03-27 12:06:30-07:00Exception in defer callback: Error: [We could not find the collection instance by name: "users", the cursor description was: {"collectionName":"users","selector":{"_id":"NcktrMkdo3CD43bKQ","services.resume.loginTokens.hashedToken":"trn5LweVOmj/gZgqWvsfnw4zSFNi3N4x+6Gej5hR/Rc="},"options":{"transform":null,"fields":{"_id":1}}}]
pdvn3
2019-03-27 12:06:30-07:00 at new ObservableCollection (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:41:19)
pdvn3
2019-03-27 12:06:30-07:00 at new RedisOplogObserveDriver (packages/cultofcoders:redis-oplog/lib/mongo/RedisOplogObserveDriver.js:37:37)
pdvn3
2019-03-27 12:06:30-07:00 at MongoConnection.<anonymous> (packages/cultofcoders:redis-oplog/lib/mongo/observeChanges.js:123:25)
pdvn3
2019-03-27 12:06:30-07:00 at MongoConnection.mongoConnectionProto._observeChanges (packages/mdg:meteor-apm-agent/lib/hijack/wrap_observers.js:164:38)
pdvn3
2019-03-27 12:06:30-07:00 at Cursor.observeChanges (packages/mongo/mongo_driver.js:947:22)
pdvn3
2019-03-27 12:06:30-07:00 at Cursor.cursorProto.(anonymous function) (packages/mdg:meteor-apm-agent/lib/hijack/db.js:131:32)
pdvn3
2019-03-27 12:06:30-07:00 at Cursor.kadira_Cursor_observeChanges [as observeChanges] (packages/mdg:meteor-apm-agent/lib/hijack/set_labels.js:84:41)
pdvn3
2019-03-27 12:06:30-07:00 at Meteor.defer (packages/accounts-base/accounts_server.js:895:36)
pdvn3
2019-03-27 12:06:30-07:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
pdvn3
2019-03-27 12:06:30-07:00 at packages/meteor.js:550:25
pdvn3
2019-03-27 12:06:30-07:00 at runWithEnvironment (packages/meteor.js:1286:24)
```

**Comment by jorgeer** [comment]
Jup, I have the same issue. These are the packages I use along with it.

**Comment by flean** [comment]
I think I figured it out. I misplaced the order of the package.

**Comment by flean** [comment]
When I removed the package it changed the load order, I didn't notice and forgot to check that. I won't close this since @jorgeer has this issue

**Comment by flean** [comment]
@jorgeer 

Make sure

packages
starts with this
cultofcoders:redis-oplog
disable-oplog@1.0.7

**Comment by jorgeer** [comment]
Hmm, I moved disable-oplog up, and that might have solved it? It was sort of hard to reproduce in the first place, but now I haven't seen it in a while

**Comment by flean** [comment]
Awesome, I'll close this then.

**Comment by kingservice** [comment]
I think its not solved yet, any one have another solution?

**Comment by minhna** [comment]
It looks like we have to put the block of these package on VERY TOP of packages file.
```
cultofcoders:redis-oplog
disable-oplog

# all other meteor packages list below this line
```

**Comment by vakhooooo** [comment]
@minhna omg thank's a lot

**Comment by joaovictornsv** [comment]
Seven years later, you all saved me! Thank you!
