### ISSUE TITLE
Couln't find the collection "users"

### ISSUE THREAD

**Issue by dnish** [cult-of-coders/redis-oplog#321]
Hey,
just installed the newest version of redis-oplog. When starting our application, I ge the following error message on the server:

```
I20190424-14:22:13.833(2)? Exception in defer callback: { Error: [We could not find the collection instance by name: "users", the cursor description was: {"collectionName":"users","selector":{"_id":"dLYkBKDsiy46rNn35","services.resume.loginTokens.hashedToken":"zXkrIlege/cNGdPE3al56dUskH3nkfsq+eUS1Y003b4="},"options":{"transform":null,"fields":{"_id":1}}}]
I20190424-14:22:13.833(2)?     at new ObservableCollection (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:41:19)
I20190424-14:22:13.833(2)?     at new RedisOplogObserveDriver (packages/cultofcoders:redis-oplog/lib/mongo/RedisOplogObserveDriver.js:37:37)
I20190424-14:22:13.833(2)?     at MongoConnection._observeChanges (packages/cultofcoders:redis-oplog/lib/mongo/observeChanges.js:123:25)
I20190424-14:22:13.834(2)?     at Cursor.observeChanges (packages/mongo/mongo_driver.js:947:22)
I20190424-14:22:13.834(2)?     at Meteor.defer (packages/accounts-base/accounts_server.js:895:36)
I20190424-14:22:13.834(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20190424-14:22:13.834(2)?     at packages/meteor.js:550:25
I20190424-14:22:13.834(2)?     at runWithEnvironment (packages/meteor.js:1286:24)
I20190424-14:22:13.834(2)?   isClientSafe: true,
I20190424-14:22:13.834(2)?   error: 'We could not find the collection instance by name: "users", the cursor description was: {"collectionName":"users","selector":{"_id":"dLYkBKDsiy46rNn35","services.resume.loginTokens.hashedToken":"zXkrIlege/cNGdPE3al56dUskH3nkfsq+eUS1Y003b4="},"options":{"transform":null,"fields":{"_id":1}}}',
I20190424-14:22:13.834(2)?   reason: undefined,
I20190424-14:22:13.834(2)?   details: undefined,
I20190424-14:22:13.834(2)?   message: '[We could not find the collection instance by name: "users", the cursor description was: {"collectionName":"users","selector":{"_id":"dLYkBKDsiy46rNn35","services.resume.loginTokens.hashedToken":"zXkrIlege/cNGdPE3al56dUskH3nkfsq+eUS1Y003b4="},"options":{"transform":null,"fields":{"_id":1}}}]',
I20190424-14:22:13.835(2)?   errorType: 'Meteor.Error' }

```

We are using Astronomy as model layer. Any idea what's going wrong?

**Comment by dnish** [comment]
https://github.com/cult-of-coders/redis-oplog/issues/317
