### ISSUE TITLE
Error Exception in onStop callback: TypeError: Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by bug249286** [cult-of-coders/redis-oplog#377]
METEOR@1.12.1

```
I20210731-02:35:16.742(7)? Exception in onStop callback: TypeError: Cannot read property 'stop' of undefined
I20210731-02:35:16.743(7)?     at ObserveMultiplexer.onStop [as _onStop] (packages/cultofcoders:redis-oplog/lib/mongo/observeChanges.js:53:35)
I20210731-02:35:16.743(7)?     at ObserveMultiplexer._stop (packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:119:14)
I20210731-02:35:16.744(7)?     at ObserveMultiplexer.removeHandle (packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:105:18)
I20210731-02:35:16.744(7)?     at ObserveHandle.stop (packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:288:23)
I20210731-02:35:16.744(7)?     at Subscription.<anonymous> (packages/mongo/collection.js:385:21)
I20210731-02:35:16.744(7)?     at runWithEnvironment (packages/meteor.js:1286:24)
I20210731-02:35:16.744(7)?     at packages/meteor.js:1299:14
I20210731-02:35:16.744(7)?     at packages/ddp-server/livedata_server.js:1158:7
I20210731-02:35:16.744(7)?     at Array.forEach (<anonymous>)
I20210731-02:35:16.744(7)?     at Function._.each._.forEach (packages/underscore.js:139:11)
I20210731-02:35:16.744(7)?     at Subscription._callStopCallbacks (packages/ddp-server/livedata_server.js:1157:7)
I20210731-02:35:16.744(7)?     at Subscription._deactivate (packages/ddp-server/livedata_server.js:1147:10)
I20210731-02:35:16.744(7)?     at packages/ddp-server/livedata_server.js:896:11
I20210731-02:35:16.744(7)?     at Map.forEach (<anonymous>)
I20210731-02:35:16.744(7)?     at Session._deactivateAllSubscriptions (packages/ddp-server/livedata_server.js:895:21)
I20210731-02:35:16.744(7)?     at packages/ddp-server/livedata_server.js:450:12
```
Thank you.

**Comment by salmanhasni** [comment]
I'm having the similar issue +1

**Comment by alexebird** [comment]
I'm having this issue on meteor 2.6.
