### ISSUE TITLE
Exception when a modifier with undefined values is used

### ISSUE THREAD

**Issue by xolott** [cult-of-coders/redis-oplog#398]
When this modifier is used, redis-log throws an exception:

```js
const modifer = {
    $addToSet: undefined
};

Collection.update(selector, modifier);
```

Exception:

```
Exception in setInterval callback: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at packages/cultofcoders:redis-oplog/lib/utils/getFields.js:12:20
    at Array.forEach (<anonymous>)
    at getFields (packages/cultofcoders:redis-oplog/lib/utils/getFields.js:10:29)
    at ns.Collection.update (packages/cultofcoders:redis-oplog/lib/mongo/Mutator.js:198:32)
    at ns.Collection.update (packages/cultofcoders:redis-oplog/lib/mongo/extendMongoCollection.js:40:35)
```

I think the issue is in this line: https://github.com/cult-of-coders/redis-oplog/blob/58ba4266f4978f061081c641efe89ce9db9b791b/lib/utils/getFields.js#L11

Something like this should work.

```js
    const isNil = (value) => value === null || value === undefined;
    Object.entries(mutator).forEach(function ([op, params]) {
        if (op[0] == '$' && !isNil(params)) {
```

A modifier with a value undefined is valid for the mongo driver. It just ignores it.

**Comment by xolott** [comment]
I created the PR #399 with what I think would fix the issue
