### ISSUE TITLE
Doesn't work well without collection2 package. It fails like this:

### ISSUE THREAD

**Issue by theodorDiaconu** [cult-of-coders/redis-oplog#87]
Exception in defer callback: TypeError: callback is not a function
I20161207-10:52:58.863(2)?     at packages/mongo/collection.js:651:5
I20161207-10:52:58.864(2)?     at packages/minimongo.js:615:7
I20161207-10:52:58.864(2)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20161207-10:52:58.864(2)?     at packages/meteor.js:445:45
I20161207-10:52:58.864(2)?     at runWithEnvironment (packages/meteor.js:1176:24)

----- on this insert ------
{ _id: 'version-refreshable',
I20161207-10:55:39.781(2)?   version: '838894363a892e333ec3da261652a326e72fb0a9',
I20161207-10:55:39.782(2)?   assets: { allCss: [ [Object] ] } } { pushToRedis: true,
I20161207-10:55:39.782(2)?   _channels: [ 'meteor_autoupdate_clientVersions' ] }

**Comment by theodorDiaconu** [comment]
added a mention for now on README.md, we all use collection2, if not, we should.
