### ISSUE TITLE
Server-side errors from direct processors unable to find id's

### ISSUE THREAD

**Issue by ramezrafla** [cult-of-coders/redis-oplog#89]
Below are the server-side stack traces .. thanks!

```
Exception in queued task: Error: Removed nonexistent document 3HENRjvrigp8Ez4yy
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
    at Session.removed (packages/ddp-server/livedata_server.js:391:10)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1273:19)
    at Object.removed (packages/mongo/collection.js:352:11)
    at Object.removed (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:94:26)
    at packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:88:13
    at Array.forEach (native)
    at PublicationEntry.send (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:87:24)
    at ObservableCollection.send (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:116:9)
    at ObservableCollection.remove (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:247:18)
    at handleRemove (packages/cultofcoders:redis-oplog/lib/processors/direct.js:52:26)
    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/direct.js:14:13)
    at Object.task (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:55:28)
    at [object Object]._.extend._run (packages/meteor.js:807:18)
    at packages/meteor.js:785:14
```

```
Exception in queued task: Error: Could not find element with id 3HENRjvrigp8Ez4yy to change
    at SessionCollectionView.changed (packages/ddp-server/livedata_server.js:188:13)
    at Session.changed (packages/ddp-server/livedata_server.js:400:10)
    at Subscription.changed (packages/ddp-server/livedata_server.js:1254:19)
    at Object.changed (packages/mongo/collection.js:349:11)
    at Object.changed (packages/cultofcoders:redis-oplog/lib/mongo/extendObserveChanges.js:89:26)
    at packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:88:13
    at Array.forEach (native)
    at PublicationEntry.send (packages/cultofcoders:redis-oplog/lib/cache/PublicationEntry.js:87:24)
    at ObservableCollection.send (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:116:9)
    at ObservableCollection.change (packages/cultofcoders:redis-oplog/lib/cache/ObservableCollection.js:185:14)
    at handleUpdate (packages/cultofcoders:redis-oplog/lib/processors/direct.js:40:34)
    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/direct.js:11:13)
    at Object.task (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:55:28)
    at [object Object]._.extend._run (packages/meteor.js:807:18)
    at packages/meteor.js:785:14
```

**Comment by ramezrafla** [comment]
So here is what is happening upon research:

We had a user that had not logged in in a while. Their profile was pointing to stale docs that were cleaned up since (we do autoclean when users login)

So upon login, the autorun publication triggers a push of non-existent id's. As the clean up happens and removes the faulty id's one by one, the autorun keeps triggering trying to locate other missing id's until all the id's are all removed.

The **solution** is to ignore non found id's -- you don't need to worry their custom channels since they are unlikely to ever exist as id's are unique and new ones will be created for new documents.

**Comment by theodorDiaconu** [comment]
@ramezrafla their local collection of the element is something we don't have access to... I believe it's good to have these errors, is there any work-around you can do to this ?

**Comment by ramezrafla** [comment]
@theodorDiaconu, this error is at the server level. It's trying to send a non-existent _id. It could be argued that it's the developer's fault for trying to push a non-existent doc. The original Meteor / Mongo pub would silently ignore it. So it's a change of behavior. Regardless of what you decide to do, I am ok with it remaining as-is, it just litters the logs and delays publication. 

**Important:** There are cases where the publication is NOT reactive, in which case a non-existent _id will result in failure of the pub.

**Comment by theodorDiaconu** [comment]
@ramezrafla if you could provide a reproduction repo for this I will be more than happy to solve it, reason is I don't know how to reproduce this.

**Comment by theodorDiaconu** [comment]
until I don't have a way to reproduce it, can't keep it open

**Comment by etyp** [comment]
@theodorDiaconu @ramezrafla I believe I've successfully re-created this issue in a sample repo. Opened a new issue https://github.com/cult-of-coders/redis-oplog/issues/276

Let me know if it's easier to re-open an older one instead.

**Comment by ramezrafla** [comment]
@etyp 
Thanks so much for reproducing it, well done! I'll comment on your issues directly
